# Usage:
# eksctl create cluster -f eks-ipv6.yaml
# eksctl delete cluster -f eks-ipv6.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: skytest
  region: ap-northeast-2
  version: "1.29"

kubernetesNetworkConfig:
  ipFamily: IPv6

iam:
  withOIDC: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

managedNodeGroups:
   - name: skytest-nodegroup
     instanceType: m5.4xlarge
     desiredCapacity: 1
     privateNetworking: true
